### ISSUE TITLE
monograph not responding correctly?

### ISSUE THREAD

**Issue by tes5884** [streetwriters/notesnook-sync-server#16]
When trying to connect my desktop app to my server, it's complaining that it can't connect to the monograph server.

`/api/health` returns `200` - so that's good

when I run the test, i get the following in the server logs:

```
monograph-server-1  | GET /api/health 200 - - 12.345 ms
monograph-server-1  | Error: No route matches URL "/api/version"
monograph-server-1  |     at getInternalRouterError (/home/node/app/node_modules/@remix-run/router/router.ts:5505:5)
monograph-server-1  |     at Object.query (/home/node/app/node_modules/@remix-run/router/router.ts:3527:19)
monograph-server-1  |     at handleDocumentRequest (/home/node/app/node_modules/@remix-run/server-runtime/dist/server.js:275:35)
monograph-server-1  |     at requestHandler (/home/node/app/node_modules/@remix-run/server-runtime/dist/server.js:160:24)
monograph-server-1  |     at /home/node/app/node_modules/@remix-run/express/dist/server.js:41:28
monograph-server-1  | ErrorResponseImpl {
monograph-server-1  |   status: 404,
monograph-server-1  |   statusText: 'Not Found',
monograph-server-1  |   internal: true,
monograph-server-1  |   data: 'Error: No route matches URL "/api/version"',
monograph-server-1  |   error: Error: No route matches URL "/api/version"
monograph-server-1  |       at getInternalRouterError (/home/node/app/node_modules/@remix-run/router/router.ts:5505:5)
monograph-server-1  |       at Object.query (/home/node/app/node_modules/@remix-run/router/router.ts:3527:19)
monograph-server-1  |       at handleDocumentRequest (/home/node/app/node_modules/@remix-run/server-runtime/dist/server.js:275:35)
monograph-server-1  |       at requestHandler (/home/node/app/node_modules/@remix-run/server-runtime/dist/server.js:160:24)
monograph-server-1  |       at /home/node/app/node_modules/@remix-run/express/dist/server.js:41:28
monograph-server-1  | }
monograph-server-1  | ErrorResponseImpl {
monograph-server-1  |   status: 404,
monograph-server-1  |   statusText: 'Not Found',
monograph-server-1  |   internal: true,
monograph-server-1  |   data: 'Error: No route matches URL "/api/version"',
monograph-server-1  |   error: Error: No route matches URL "/api/version"
monograph-server-1  |       at getInternalRouterError (/home/node/app/node_modules/@remix-run/router/router.ts:5505:5)
monograph-server-1  |       at Object.query (/home/node/app/node_modules/@remix-run/router/router.ts:3527:19)
monograph-server-1  |       at handleDocumentRequest (/home/node/app/node_modules/@remix-run/server-runtime/dist/server.js:275:35)
monograph-server-1  |       at requestHandler (/home/node/app/node_modules/@remix-run/server-runtime/dist/server.js:160:24)
monograph-server-1  |       at /home/node/app/node_modules/@remix-run/express/dist/server.js:41:28
monograph-server-1  | }
```

**Comment by 1itt1eB0y** [comment]
same issue

**Comment by dyw770** [comment]
monograph server a new version of the image has not been released yet.

**Comment by Iceman248** [comment]
I can't even connect with a new app since it now requires monograph server URL which doesn't work.

**Comment by ibaraki-douji** [comment]
it's published you can close the issue now

**Comment by tes5884** [comment]
Yeah, I’ll close this issue. It doesn’t complain anymore. But now we have a diff issue, the app just keeps showing that it’s syncing, and doesn’t actually sync anything. Will open a new issue….
